title: web & speck
email: hello@webundspeck.com
url: https://webundspeck.github.io

description: >-
  web & speck is a community of developers, designers, tech-enthusiasts and
  tech-startups in Innsbruck.

facebook_username: webundspeck
twitter_username: webundspeck
meetup_username: webundspeck
github_username: webundspeck

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
